name: Random Coding Joke Action
on:
  pull_request:
    types:
      - opened

jobs:
  generate_joke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch random coding joke
        id: joke
        run: |
          joke=$(curl -s https://official-joke-api.appspot.com/jokes/programming/random | jq -r '.[0].setup')
          punchline=$(curl -s https://official-joke-api.appspot.com/jokes/programming/random | jq -r '.[0].punchline')
          echo "::set-output name=joke::$joke"
          echo "::set-output name=punchline::$punchline"

      - name: Comment with random coding joke
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const joke = '${{ steps.joke.outputs.joke }}';
            const punchline = '${{ steps.joke.outputs.punchline }}';
            const comment = `😄 Random Coding Joke 😄\n\n${joke}\n\n${punchline}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

